/// TMDB `original_language` values (ISO 639-1, plus TMDB's non-standard
/// 'cn' for Cantonese). Expanded 2026-08-15 from an initial 21-language
/// list that covered only one Indian language (Hindi) despite the app
/// being used for Korean, Japanese, and Indian-language content -- every
/// major Indian regional-language film/TV industry is now included,
/// alongside broader world-cinema coverage.
const List<Map<String, String>> supportedLanguages = [
  {'code': 'en', 'name': 'English'},
  {'code': 'ja', 'name': 'Japanese'},
  {'code': 'fr', 'name': 'French'},
  {'code': 'es', 'name': 'Spanish'},
  {'code': 'de', 'name': 'German'},
  {'code': 'ko', 'name': 'Korean'},
  {'code': 'it', 'name': 'Italian'},
  {'code': 'pt', 'name': 'Portuguese'},
  {'code': 'zh', 'name': 'Mandarin'},
  {'code': 'cn', 'name': 'Cantonese'},
  {'code': 'ru', 'name': 'Russian'},
  {'code': 'sv', 'name': 'Swedish'},
  {'code': 'pl', 'name': 'Polish'},
  {'code': 'da', 'name': 'Danish'},
  {'code': 'no', 'name': 'Norwegian'},
  {'code': 'nl', 'name': 'Dutch'},
  {'code': 'tr', 'name': 'Turkish'},
  {'code': 'th', 'name': 'Thai'},
  {'code': 'ar', 'name': 'Arabic'},
  {'code': 'vi', 'name': 'Vietnamese'},
  // Indian languages -- each has its own major film/TV industry on TMDB.
  {'code': 'hi', 'name': 'Hindi'},
  {'code': 'ta', 'name': 'Tamil'},
  {'code': 'te', 'name': 'Telugu'},
  {'code': 'ml', 'name': 'Malayalam'},
  {'code': 'kn', 'name': 'Kannada'},
  {'code': 'bn', 'name': 'Bengali'},
  {'code': 'mr', 'name': 'Marathi'},
  {'code': 'pa', 'name': 'Punjabi'},
  {'code': 'gu', 'name': 'Gujarati'},
  {'code': 'ur', 'name': 'Urdu'},
  {'code': 'or', 'name': 'Odia'},
  {'code': 'as', 'name': 'Assamese'},
  // Broader world-cinema coverage.
  {'code': 'id', 'name': 'Indonesian'},
  {'code': 'ms', 'name': 'Malay'},
  {'code': 'tl', 'name': 'Filipino'},
  {'code': 'fa', 'name': 'Persian'},
  {'code': 'he', 'name': 'Hebrew'},
  {'code': 'el', 'name': 'Greek'},
  {'code': 'hu', 'name': 'Hungarian'},
  {'code': 'cs', 'name': 'Czech'},
  {'code': 'ro', 'name': 'Romanian'},
  {'code': 'fi', 'name': 'Finnish'},
  {'code': 'uk', 'name': 'Ukrainian'},
  {'code': 'sr', 'name': 'Serbian'},
  {'code': 'hr', 'name': 'Croatian'},
  {'code': 'bg', 'name': 'Bulgarian'},
  {'code': 'sk', 'name': 'Slovak'},
  {'code': 'is', 'name': 'Icelandic'},
  {'code': 'ka', 'name': 'Georgian'},
  {'code': 'hy', 'name': 'Armenian'},
  {'code': 'mn', 'name': 'Mongolian'},
  {'code': 'my', 'name': 'Burmese'},
  {'code': 'km', 'name': 'Khmer'},
  {'code': 'lo', 'name': 'Lao'},
  {'code': 'ne', 'name': 'Nepali'},
  {'code': 'si', 'name': 'Sinhala'},
  {'code': 'sw', 'name': 'Swahili'},
  {'code': 'af', 'name': 'Afrikaans'},
  {'code': 'ca', 'name': 'Catalan'},
];
